### PR TITLE
ignoring files that match regular expressions

### PR DESCRIPTION
**Pull request by stevenreinisch**
ignoring files that match regular expressions specified by '--ignore_file_patterns'

### CODE REVIEW

**Comment by nakiostudio** [comment]
Hi again! nothing to mention code-wise but I think this feature can be implemented by simply analyzing the regular expressions included on every single row within the ignore file if these contain one. The motivation behind this is to keep the list of params accepted by xcov as small as possible. What do you think?

**Comment by stevenreinisch** [comment]
Hi,

you mean doing it like this in the ignore file:

```
- SomeExcludedFile.swift
- .*View\.(?:m|swift)$
```

and then in `source.rb`:

`@ignored = Xcov.ignore_list.any? { |pattern| name =~ Regexp.new(pattern) }`

This would be better since it does not add a new param - you're right.

**Comment by nakiostudio** [comment]
Something like the following and then filter out the filenames ending by `*View.swift`
```
- SomeExcludedFile.swift
- .*View.swift
```

**Comment by stevenreinisch** [comment]
I updated the code.

**Comment by nakiostudio** [comment]
Great, I will polish a couple of things and release 0.7 including your changes. Thank you @stevenreinisch 🍻

**Pull request merged**
