### PR TITLE
Escaping

### PR DESCRIPTION
**Pull request by michaelharro**
should fix this issue https://github.com/nakiostudio/xcov/issues/13. I'm not a ruby guy so I am not sure how to test it properly so test before you merge this

### CODE REVIEW

**Comment by michaelharro** [comment]
I tried `bundle exec rake test` but got 
```
rake aborted!
Don't know how to build task 'test' (see --tasks)
```
So please test this.

From what I can gather Ruby requires it's paths to be unescaped but shell needs them escaped. So I put a note in the README to ask users to provide unescaped paths so you can use them with Ruby methods but then escaped all the paths before having fastlane run your command on the shell. Let me know if that worked.

**Comment by nakiostudio** [comment]
Hi @michaelharro :wave: 

Many thanks for this! I'm on holiday right now without access to my laptop but I will review this and eventually merge it as soon as I can. 

Thanks!

**Comment by michaelharro** [comment]
No problem. Have a great holiday.

**Comment by nakiostudio** [comment]
Hey again @michaelharro 👋 and sorry again for the delay reviewing your PR.

In some cases it might not work but makes sense, in fact FastlaneCore internally shells capes the paths supplied. I will prepare a release letting the users know that the change may break current integrations.

Thank you!

**Comment by michaelharro** [comment]
No problem. Thanks for looking at it.

Yes, I had a look through the fastlane code base and I saw that in some places it escapes the paths for you and others it doesn't. I made an issue https://github.com/fastlane/fastlane/issues/5458 and hopefully it will be changed so that paths are always given to fastlane actions unescaped and they only need to be escaped before giving a command to shell to run. I think that will resolve issues with systems that need their paths escaped (ie Jenkins, which uses the human readable job name as the folder name).

**Comment by nakiostudio** [comment]
That's awesome @michaelharro, I will keep an eye on your PR!

**Pull request merged**
