### PR TITLE
Measure coverage considering the number of lines

### LINKED ISSUE #51: Project's code coverage should respect number of lines per framework.
First of all, I really like this project. However I think calculating project's code coverage by simply averaging libraries' code coverages can be misleading. In my opinion it should be calculated using formula `total number of lines covered / total number of lines`.

Furthermore I would love to see `[number of lines covered] / [number of lines]` in reports as well.

### PR DESCRIPTION
**Pull request by thelvis4**
This patch changes the way project coverage and target coverages are computed.
Coverage is computed using formula `number of covered lines` / `number of executable lines`.

This partially resolves #51 

Note:  `xcov-core` was updated to version 0.4

### CODE REVIEW

**Comment by thelvis4** [comment]
@mpodeszwa Could you please test this? I've tested it on my side, but a double check is always welcome. 😊 
Please let me know if you need any help.

**Comment by tikitu** [comment]
What's the easiest way to find the number of executable lines in a file? (I'm doing a simple sanity-check of the arithmetic.)

**Comment by thelvis4** [comment]
I'm afraid there is no easy way to find the number of executable lines. 😞

You can count the number of executable lines by looking in source code. But this is pretty error prone as sometimes Xcode doesn't count the closing braces as executable lines.

One way you can get the exact number of executable lines it to run `xcov-core` against `.xccoverage` file with `--include-lines-info` option enabled and  count the lines from the JSON created as output by `xcov-core`.
For example:
`xcov-core/bin/xcov-core -s /path/to/build/Logs/Test/some-id-here.xccoverage -o report.json --include-lines-info`

**Comment by tikitu** [comment]
Welp. On the one hand this looks like a bug:

* MDAppCore.framework 90% 
 - Displaying the home page.swift 76% 
 - Coordinating independent app features.swift 80% 

Those are the only two swift files in the framework: it shouldn't be possible for the aggregated coverage to be more than *all* individual coverage percentages.

On the other hand, Xcode reports exactly the same (afaics buggy) numbers. So perhaps we score that as a win for new-style `xcov`. (And a :man_shrugging: for me...)

**Comment by thelvis4** [comment]
@tikitu That's really weird. 😕 
> Those are the only two swift files in the framework

Is there, by any chance, any Obj-C file?

**Comment by tikitu** [comment]
> Is there, by any chance, any Obj-C file?

There is not. (Well, there's the framework header.) Weird huh? But like I say, since Xcode gives the same oddity, probably not `xcov`'s problem.

I've run a few more and I'm getting *exactly* the same numbers in `xcov` (under `fastlane`) as in Xcode 7.3 for file and framework percentages. (It's so reliable that I'm wondering if I'm not testing the right thing: I would have expected a 1-percent slip *somewhere* from rounding errors.)

I do get a big "0" for the total ("Keep calm and leave the boat") though: maybe that's one to double-check on your end.

**Comment by thelvis4** [comment]
@tikitu Xcov uses the same file (.xccoverage) as Xcode to display the coverage. So, file percentage should always be the same, as we don't alter the data for files in any way. 
Target percentages, though, might differ if you exclude some of the files from reports.

> I do get a big "0"

I can't reproduce this on my side. Could you, please, describe your project's structure?
Or, if it doesn't contain any confidential info, could you please share it with me, so that I could figure out the issue?

**Comment by tikitu** [comment]
The 0 might be something quite simple: I tweaked the Fastfile to run a test scheme instead of the (tests of the) main app scheme: perhaps that's it? (Fastfile attached, I ran `tests_and_coverage`.)

If not: my project's structure is technically described as "a mess" (which I can't share with you directly, sorry). It's mixed Swift/Obj-C with about 10 internal frameworks managed by hand in Xcode and a similar number of external dependencies managed by Cocoapods: lots of potential for edge cases. 

I've uploaded the `.xccoverage` files from three recent test runs, perhaps they can be helpful: [1](http://www.logophile.org/priv/0D78AACD-A0C1-432F-BB06-9550CBBEB15A.xccoverage), [2](http://www.logophile.org/priv/9A6B5212-4F69-484E-B4B9-46DF8FC171B9.xccoverage), [3](http://www.logophile.org/priv/
[Fastfile.txt](https://github.com/nakiostudio/xcov/files/695499/Fastfile.txt)
AFEE7D4A-163B-4C21-A222-A6C4A88E24C0.xccoverage). I'm happy to dig for more if there's something more specific you'd like to see, but I won't be able to today (CET) I'm afraid.

**Comment by thelvis4** [comment]
@tikitu Thank you very much for providing `.xccoverage` files.
It helped me to catch the "big 0" bug. 🙌 

Note: Using `MDAppCoreTests` as a test scheme should work well.

**Pull request merged**
