### PR TITLE
Feature/exclude targets

### PR DESCRIPTION
**Pull request by stevenreinisch**
User can exclude targets from report by specifying a comma separated list of targets with --exclude_targets

### CODE REVIEW

**Comment by nakiostudio** [comment]
Hi @stevenreinisch 👋 I'm really pleased that you've decided to tackle this feature requests, thanks!

Nothing to mention about this PR, please squash the commits into a single one, ensure that the branch is on top of master and we are ready to go 👍

**Comment by stevenreinisch** [comment]
I squashed the commits.

**Comment by nakiostudio** [comment]
Great, thanks!

**Comment by mike011** [comment]
Wow quick turn around, it worked, I was able to ignore the submodules, thank you so much.

**Pull request merged**
