### PR TITLE
update read me

### PR DESCRIPTION
**Pull request by bugnaum**
Percentage value should be float, otherwise it'll throw an error. I follow the example and faced this error on my CI. That's why I created this PR, so next user won't get this error! :)

```
'minimum_coverage_percentage' value must be a Float! Found Fixnum instead.
```

### CODE REVIEW

**Comment by nakiostudio** [comment]
Good point @bugnaum
Thanks for taking the time and contribute 🙌

**Comment by thelvis4** [comment]
@bugnaum Just out of curiosity, could you share with us your script calling `xcov` please?
I tried to run xcov (latest version) passing `--minimum_coverage_percentage 75` and it was converted into a Float. 😕 
I'm trying to figure out when we run into this issue.

**Comment by bugnaum** [comment]
@thelvis4 yes, for sure I can. However, I'm out of office now and tomorrow is my day off, so only on next Monday because we use an GitHub enterprise version that can only be reached trough company internet. By now, I can tell you that we are using xcov on our Swift 3 project. I created a CI (Jenkins) that calls a Fastfile and on it. This fastfile has some lanes and one of them is xcov. I'll post the script here on next Monday. :)

**Comment by thelvis4** [comment]
@bugnaum Mentioning that you called `xcov` from a Fastfile was enough to help me reproduce the issue. ☺️
Thank you!

**Comment by bugnaum** [comment]
@thelvis4 awesome! 😄

**Pull request merged**
